version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: deilify
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"

  userservice:
    build: ./del-backend-userservice
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/deilify
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8081:8081"
    depends_on:
      - mysql
    networks:
      - backend
      
  odermanagementservice:
    build: ./del-backend-ordermanagementservice
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/deilify
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8084:8084"
    depends_on:
      - mysql
    networks:
      - backend

networks:
  backend:
    driver: bridge
